### ISSUE TITLE
11ac driver?

### ISSUE THREAD

**Issue by shivang94** [SVoxel/R9000#3]
Hi,

This is more of a question than an issue. I am planning to build your firmware for my R9000 and wanted to enable the ath10k debugging and tracing options (That's why I am planning to build from source instead of just using your released firmware).

My question comes from the fact that I see in the config that the ath10k module is not enabled by default. Does this router use some other module for its 11ac operation?

**Comment by SVoxel** [comment]
You will not be able to build fully functional firmware from this repo. The same as from NG GPL source codes:

https://kb.netgear.com/2649/NETGEAR-Open-Source-Code-for-Programmers-GPL

See details here:

https://www.snbforums.com/threads/custom-firmware-build-for-r9000.40125/page-11#post-430729

You may contact me on SNB forums.

P.S. as far as I know ath10k driver for R9000 is inside enclosed QCA firmware.
